update

diff --git a/tmux/bin/tmux-config b/tmux/bin/tmux-config
--- a/tmux/bin/tmux-config
+++ b/tmux/bin/tmux-config
@@ -16,17 +16,15 @@ if [ "$1" = "--bootstrap" ]; then
 
 	read -r -d '' LOADER <<- EOF
 	# Generated by tmux-config. Please edit the file at '${TMUX_CONFIG_INPUT/$HOME/\~}'.
-	run-shell "${TMUX_CONFIG_PATH}"
+	run-shell "${TMUX_CONFIG_PATH/$HOME/\~}"
 	EOF
 
 	# copy the tmux configuration script to requested path
-	if [ ! -f "${TMUX_CONFIG_PATH}" ]; then
-		mkdir -p "$(dirname "${TMUX_CONFIG_PATH}")"
-		cp "${TMUX_CONFIG_SOURCE}" "${TMUX_CONFIG_PATH}" || {
-			echo "Failed to copy tmux-config to '${TMUX_CONFIG_PATH}'"
-			exit 1
-		}
-	fi
+	mkdir -p "$(dirname "${TMUX_CONFIG_PATH}")"
+	cp "${TMUX_CONFIG_SOURCE}" "${TMUX_CONFIG_PATH}" || {
+		echo "Failed to copy tmux-config to '${TMUX_CONFIG_PATH}'"
+		exit 1
+	}
 
 	# if it looks like we've never added an autoloader, this is likely the
 	# user's own '.tmux.conf' file
@@ -117,6 +115,7 @@ if [ "${TMUX_CONFIG_INPUT}" -nt "${TMUX_CONFIG_OUTPUT}" ]; then
 		process-line "${LINE}" "${I}"
 		I+=1
 	done < "${TMUX_CONFIG_INPUT}"
+	mkdir -p "$(dirname "${TMUX_CONFIG_OUTPUT}")"
 	printf "%s\n" "${DOCUMENT[@]}" > "${TMUX_CONFIG_OUTPUT}"
 fi
 
